# Generated by Django 4.2.6 on 2024-06-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('Call', 'Call'), ('Meeting', 'Meeting')], max_length=50),
        ),
    ]
