# Generated by Django 4.2.6 on 2024-06-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_interaction_interaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Qualification', 'Qualification'), ('Analysis', 'Analysis'), ('Proposal', 'Proposal'), ('Negotiation', 'Negotiation'), ('Won', 'Won'), ('Lost', 'Lost')], max_length=50),
        ),
    ]
