# Generated by Django 4.2.6 on 2024-06-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_opportunity_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='date',
            field=models.DateField(),
        ),
    ]
